import{a as v,S as q,i}from"./assets/vendor-DcHCnVjq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="51148638-4215382d54794cb096cce3e5a",B="https://pixabay.com/api/";async function d(t,o){const n={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await v.get(B,{params:n})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const o=t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:c,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${r}</p>
        <p class="info-item"><b>Views:</b> ${c}</p>
        <p class="info-item"><b>Comments:</b> ${w}</p>
        <p class="info-item"><b>Downloads:</b> ${S}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",o),E.refresh()}function M(){m.innerHTML=""}function p(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function b(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}const R=document.querySelector(".form"),$=document.querySelector(".load-more-btn");let u="",a=1;const L=15;R.addEventListener("submit",O);$.addEventListener("click",x);async function O(t){t.preventDefault();const o=t.currentTarget,n=o.elements["search-text"].value.trim();if(n===""){i.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}u=n,a=1,M(),l(),p();try{const s=await d(u,a);if(s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(s.hits),o.reset(),s.totalHits>L*a?b():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(s){console.error(s),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}}async function x(){a+=1,l(),p();try{const t=await d(u,a);g(t.hits),H(),t.totalHits>L*a?b():(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.error(t),i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{y()}}function H(){const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
